all: src  

src:
	( cd .active ; make src )
	( cd .active ; make arc )

clean:
	( cd .active; make clean )

cleanall:
	( cd _none ; make cleanall )
	( cd _AF ; make cleanall)
	( cd _GS ; make cleanall)

# DO NOT DELETE THIS LINE -- make depend depends on it.
