all: src

src:
	( cd .active ; make src )
	( cd .active ; make arc )

clean:
	( cd .active ; make clean )

cleanall:
	( cd _Ohm_generalized ; make cleanall )
	( cd _Ohm ; make cleanall )
	( cd _none ; make cleanall )
	( cd doc ; make clean )

# DO NOT DELETE THIS LINE -- make depend depends on it.
