all: src

src:
	( cd .active ; make src )
	( cd .active ; make arc )


clean:
	( cd .active ; make clean )

cleanall:
	( cd _Gupta-Yos ; make cleanall )
	( cd _Dixon-Lewis ; make cleanall )
	( cd _Capitelli ; make cleanall )
	( cd doc ; make clean )

# DO NOT DELETE THIS LINE -- make depend depends on it.
