all: src


clean:
	( cd Favre_Averaging; make clean )
	( cd Plasma_Model; make clean )
	( cd Plasma_Model2; make clean )
	( cd Performance_Parameters; make clean )
	( cd MHD_Quasi1D; make clean )
	( cd Axisymmetric_Theory; make clean )
	( cd Transport_Equations; make clean )

# DO NOT DELETE THIS LINE -- make depend depends on it.
