all: src

src:
	( cd .active ; make src )
	( cd .active ; make arc )

clean:
	( cd .active ; make clean )

cleanall:
	( cd doc ; make clean )
	( cd _Air_1s_0r ; make cleanall )
	( cd _Air_2s_0r ; make cleanall )
	( cd _Air_4s_13r ; make cleanall )
	( cd _Air_TEST_3s_0r ; make cleanall )
	( cd _He_Air_3s_0r ; make cleanall )
	( cd _H2_Air_3s_0r ; make cleanall )
	( cd _Air_Plasma_8s_28r_Macheret ; make cleanall )
	( cd _Air_Plasma_12s_42r_Dunn-Kang-Macheret ; make cleanall )
	( cd _Air_Plasma_6s_15r ; make cleanall )
	( cd _Air_Plasma_11s_31r_Dunn-Kang ; make cleanall )
	( cd _Air_Plasma_11s_Park ; make cleanall )
	( cd _N2_Plasma_3s_3r ; make cleanall )
	( cd _H2_Air_9s_20r_Jachimowsky ; make cleanall )
	( cd _H2_Air_9s_Smith ; make cleanall )
	( cd _H2_Air_Plasma_17s_Lenard-Smith ; make cleanall )
	( cd _H2_Air_Plasma_14s_47r_Jachimowsky-Macheret ; make cleanall )
	( cd _H2_Air_Plasma_18s_78r_Jachimowsky-Dunn-Kang-Macheret ; make cleanall )
	( cd _C3H8_Air_16s_23r_Kundu ; make cleanall )
	( cd _C12H23_Air_16s_23r_Kundu ; make cleanall )
	( cd _CH4_Air_20s_52r_Yungster ; make cleanall )
	( cd _Cs_Air_Plasma_13s_Lenard ; make cleanall )
	( cd _CO2_Plasma_23s_Park ; make cleanall )


# DO NOT DELETE THIS LINE -- make depend depends on it.
