all: src

src:
	( cd .active ; make src )
	( cd .active ; make arc )

clean:
	( cd .active ; make clean )

cleanall:
	( cd doc ; make clean )
	( cd _Air_1s_0r ; make cleanall )
	( cd _Air_2s_0r ; make cleanall )
	( cd _Air_5s ; make cleanall )
	( cd _Air_TEST_3s_0r ; make cleanall )
	( cd _Air_Plasma_6s_15r ; make cleanall )
	( cd _Air_Plasma_8s ; make cleanall )
	( cd _Air_Plasma_11s ; make cleanall )
	( cd _Air_Plasma_12s ; make cleanall )
	( cd _N2_Plasma_4s ; make cleanall )
	( cd _H2_Air_3s_0r ; make cleanall )
	( cd _H2_Air_9s ; make cleanall )
	( cd _H2_Air_13s ; make cleanall )
	( cd _H2_Air_Plasma_13s ; make cleanall )
	( cd _H2_Air_Plasma_18s ; make cleanall )
	( cd _H2_Cs_Air_Plasma_15s ; make cleanall )
	( cd _C3H8_Air_16s_23r_Kundu ; make cleanall )
	( cd _C12H23_Air_16s_23r_Kundu ; make cleanall )
	( cd _C12H23_Cs_Air_Plasma_21s ; make cleanall )
	( cd _CH4_Air_20s_52r_Yungster ; make cleanall )
	( cd _Cs_Air_Plasma_11s ; make cleanall )
	( cd _Cs_Air_Plasma_15s ; make cleanall )
	( cd _CO2_Plasma_23s_Park ; make cleanall )
	( cd _C2H4_Air_3s_0r ; make cleanall )
	( cd _C2H4_Air_23s ; make cleanall )
	( cd _C2H4_Air_30s ; make cleanall )
	( cd _C2H4_Air_Plasma_36s ; make cleanall )
	( cd _He_Air_3s_0r ; make cleanall )
	( cd _H2_He_CH4_Plasma_13s ; make cleanall )


# DO NOT DELETE THIS LINE -- make depend depends on it.
